### PR TITLE
delete fix broken placeholder(#19)

### PR DESCRIPTION
**Pull request by nightmorning**
Do you think it's okay for me to comment out this code?

### CODE REVIEW

**Comment by bobiverse** [comment]
How do you think? Should we keep such code? (and commit _Left_ and _Right_ brackets fix) or we should move to strict parsing and allow only `{{Placeholder}}`.

I vote for strict parsing and try to find examples where placeholder gets cut in half or lose some brackets.

**Comment by nightmorning** [comment]
I hope to strictly parse and let users actively discover that the placeholder is incorrect

**Comment by bobiverse** [comment]
Then let's do that. 
Please remove that code and also whole function of fixing brackets. :pray: 
I'll approve pull request then, ok?

**Comment by nightmorning** [comment]
👌

**Pull request closed without merging**
